spring:
  profiles:
# 	active: dev 不生效获取maven配置
    active: dev
  http:
    encoding:
    charset: UTF-8
    enabled: true
    force: true
    
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.xdd.entity
  mapperLocations: classpath:mappers/*.xml    
 
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql  
     
logging:
  config: classpath:logback-spring.xml
  # dao下目录配置debug模式，代码如下，这样配置sql语句会打印，其他还是正常info级别
  level:
    com.qsqx: debug
    org:
      mybatis: debug